name: The Marketing Counselors
favicon: null
layout_spectrum: 0.50414
typography_spectrum: 0.49729
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0c0304'
    - '#d4d9d3'
    - '#ecac42'
    - '#848e73'
    - '#b22200'
  brandStrength: 0.5
  lightness: 0.48205712460912764
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
