name: The Marketing Counselors
favicon: null
layout_spectrum: 0.50414
typography_spectrum: 0.49729
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#643796'
    - '#f7941d'
    - '#00a88e'
    - '#fff0cf'
    - '#a5a7b0'
  brandStrength: 0.5
  lightness: 0.48205712460912764
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
